# Generated by Django 5.0.3 on 2024-03-19 17:35

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('serial_no', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Item',
            },
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Lab',
            },
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': [django.db.models.functions.text.Upper('item__name')]},
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='category_inf',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='descript_inf',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='lab_name_no',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='quantity_of',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='ser_prod_no',
        ),
        migrations.AddField(
            model_name='inventory',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='threshold_high',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='threshold_low',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='inventory',
            table='Inventory',
        ),
        migrations.AddField(
            model_name='inventory',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.item'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='lab',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.lab'),
        ),
    ]
