# Generated by Django 5.0.3 on 2024-03-19 17:44

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_item_lab_alter_inventory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'managed': False, 'ordering': [django.db.models.functions.text.Upper('item__name')]},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='lab',
            options={'managed': False},
        ),
    ]
